# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='city',
            field=models.CharField(default='n/a', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchdata',
            name='state',
            field=models.CharField(default='n/a', max_length=128),
            preserve_default=False,
        ),
    ]
